-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 13:12:51 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema roadmaps
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema roadmaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roadmaps` DEFAULT CHARACTER SET utf8 ;
USE `roadmaps` ;

-- -----------------------------------------------------
-- Table `roadmaps`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadmaps`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roadmaps`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roadmaps`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(128) NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  `description` TEXT NOT NULL,
  `parent_task_id` INT NULL,
  `done` TINYINT NOT NULL,
  `project_id` INT NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_task_idx` (`parent_task_id` ASC),
  INDEX `fk_task_project1_idx` (`project_id` ASC),
  CONSTRAINT `fk_task_task`
    FOREIGN KEY (`parent_task_id`)
    REFERENCES `roadmaps`.`task` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_task_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `roadmaps`.`project` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
